project:
  type: website
  output-dir: docs

website:
  navbar:
    search: false
    background: transparent
    collapse: false

    left:
      - text: "Bedirhan Avdancı"
        href: index.qmd

    right:
      - text: "Blog"
        href: posts.qmd
      - text: "CV"
        href: CV_AvdancıBedirhan.pdf
      - text: "Contact"
        href: mailto:bedirhan.avd@gmail.com

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: false
    mainfont: "Charter"
    fontsize: 1rem
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="m0aiTxI7MKTvXcF60qY7x8Kb2k47ci3O4NkXy0V8b9o" />
