project:
  type: website
  output-dir: docs

website:
  title: "Bedirhan AvdancÄ±"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "CV"
        menu:
          - text: "English"
            url: CV_BedirhanAvdanci.pdf
    right:
      - icon: twitter
        href: https://twitter.com/bedirhansoil
      - text: "Contact"
        menu:
          - text: "bedirhan.avd@gmail.com"
            href: "mailto:bedirhan.avd@gmail.com"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



